version: '2'

services:
  web:
    build: 
      dockerfile: Dockerfile
    container_name: web
    ports:
      - "8081:8080"
  web2:
    build: 
      dockerfile: Dockerfile
    container_name: web2
    ports:
      - "8082:8080"
  web3:
    build: 
      dockerfile: Dockerfile
    container_name: web3
    ports:
      - "8083:8080"